In [61]:
import numpy as np

**1) Alturas**

i. No trecho de código abaixo, crie um ndarray chamado altura_em_centimetros transformando a lista lista_de_alturas em um ndarray do numpy com a função np.array()

ii. Crie um outro objeto altura em metros, com os valores de altura_em_centimetros convertidos para metros.

In [62]:
#exercício 1.i 
lista_de_centimetros = list(range(170, 190, 5))
# Vale resaltar que a lista de altura é um rage de 5 a 5 cm, começando de 170 e terminado em 190.
altura_em_centimetros = np.array(lista_de_centimetros)
print(altura_em_centimetros)

[170 175 180 185]


In [63]:
# exercício 1.ii
altura_em_metros = altura_em_centimetros / 100
print(altura_em_metros)

[1.7  1.75 1.8  1.85]


# **2) IMC**

i. Considere que pesos em Kg dessas pessoas, na mesma ortem, estão na lista pesos lista_pesos = [70, 75, 80, 85]. Crie um ndarray chamado pesos com a função np.array() que contenha esses valores.

ii. Utilizando o objeto que contém as alturas em metros e esse objeto que contém os respectivos pesos em quilos, calcule o IMC desses indivíduos utilizando a aritmética de arrays e guarde os resultados em um objeto chamado imc.

In [64]:
# exercício 2.i

lista_pesos = [70, 75, 80, 85]
pesos = np.array(lista_pesos)
print(pesos)

[70 75 80 85]


In [65]:
# exercício 2.ii

#formúla do IMC
imc = pesos / (altura_em_metros*altura_em_metros)

#como já usamos as variáveis com esses nomes, facilita, agora é só mostrar o resultado
print(imc)

[24.22145329 24.48979592 24.69135802 24.83564646]


# **3) Endividamento**

Cálculos de novas variáveis como endividamento total e comprometimento de renda são essenciais para a construção de modelos financeiros em ciência de dados. Áreas não financeiras terão cálculos semelhantes também. Vamos praticar:

Considere que o seguinte ndarray contém os dados de 4 pessoas, total a ser pago a empréstimos mensalmente e renda familiar:

i. Transforme a lista de listas dados_financeiros no ndarray nd_financeiros.

dados_financeiros[[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]]

ii. Utilize o método .transpose e certifique-se de que esse ndarray tenha uma linha por indivíduo e uma coluna por informação. Utilizando a indexação do numpy, imprima no output a segunda linha do array, depois a segunda coluna.

iii. Pratique aritmética com nearrays e calcule o endividamento total como:
endividamentototal=custo_fixo + dívida_financeira / renda_familiar 
Guarde os resultados em uma variável chamada endividamento_total e verifique os resultados imprimindo o conteúdo dessa variável no output.

iv. Considere que há um erro de digitação que precisa ser corrigido: 3o indivíduo na verdade não possui renda familiar de R$7.000,00, mas    sim R$ 10.000,00. Corrija esse valor e refaça os cálculos.

In [66]:
# exercício 3.i

dados_financeiros = [[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]]

#transformando em array

nd_financeiros = np.array(dados_financeiros)
print(nd_financeiros)
print(type(nd_financeiros))

[[ 3000  2500  1000 10000]
 [ 1000  2500  3000  5000]
 [ 6000  5500  7000 16000]]
<class 'numpy.ndarray'>


In [72]:
# exercícios 3.ii

nd_financeiros = nd_financeiros.transpose()
# O transpose inverte o array 
print(nd_financeiros)
print(type(nd_financeiros))

[[ 3000  2500  1000 10000]
 [ 1000  2500  3000  5000]
 [ 6000  5500 10000 16000]]
<class 'numpy.ndarray'>


In [73]:
#mostrar a segunda linha que agora é coluna
nd_financeiros[:,1]

array([2500, 2500, 5500])

In [74]:
#mostrar a segunda linha que antes era coluna
nd_financeiros[1,:]

array([1000, 2500, 3000, 5000])

In [75]:
# exercício 3.iii

endividamento_total = (nd_financeiros[:,0] + nd_financeiros[:,1]) / nd_financeiros[:,2]
print(endividamento_total)

[5.5        1.16666667 1.15      ]


In [76]:
#exercício 3.iv

#corrigindo de 7mil para 10mil a rende do terceiro elemento
nd_financeiros[2,2] = 10000
print(nd_financeiros)

[[ 3000  2500  1000 10000]
 [ 1000  2500  3000  5000]
 [ 6000  5500 10000 16000]]


In [77]:
# refazendo o endividamento total

endividamento_total = (nd_financeiros[:,0] + nd_financeiros[:,1]) / nd_financeiros[:,2]
print(endividamento_total)

[5.5        1.16666667 1.15      ]


**4) É muito comum precisarmos identificar valores especiais e darmos tratamento a eles quer seja alterando-os quer seja descartando-os.**

O trecho de código abaixo gera um ndarray com números pseudo aleatórios. Considere que para efeitos do estudo que virá, devemos desconsiderar valores iguais a zero. Sendo assim:

i) crie um objeto bool_zero que traga uma sequencia de booleanos do mesmo tamanho que o objeto poi, e que vale True quando o valor de poi é zero, e False caso contrário.

ii) Conte quantos valores zero existem. Lembre-se de que no final das contas, True vale 1 para o Python, e False vale zero, então uma boa dica seria usar a função sum().

iii) Utilize a indexação booleana que você aprendeu para criar uma variável poi_nao_zero que aponta para os elementos de poi diferentes de zero. Dica: você vai pode inverter os elementos do objeto que criou em ii) ou escrever a comparação adequada.

In [80]:
# objeto poi : o np.random.seed é um random porém ele gera sempre o mesmo random

np.random.seed(1234)
poi = np.random.poisson(3, 100)
print(poi)
print(type(poi))


[3 3 6 2 4 5 4 4 2 0 3 3 2 8 2 3 3 3 0 4 4 2 6 6 0 3 4 3 5 2 1 3 2 2 3 2 4
 4 5 7 3 5 3 3 2 2 3 6 2 2 4 3 5 2 5 3 0 2 1 1 4 4 4 6 2 4 1 2 5 5 3 4 1 4
 1 1 7 1 2 1 3 7 0 4 4 0 6 1 3 4 2 5 4 5 5 3 4 6 8 2]
<class 'numpy.ndarray'>


In [81]:
# exercício 4.i

#encontrando os valores iguais a 0

bool_zero = poi == 0
print(bool_zero)

[False False False False False False False False False  True False False
 False False False False False False  True False False False False False
  True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False  True False False False
 False False False False False False False False False False False False
 False False False False False False False False False False  True False
 False  True False False False False False False False False False False
 False False False False]


In [82]:
# exercício 4,ii

# contando os zeros

sum(bool_zero)

6

In [84]:
# exercício 4.iii

poi_nao_zero = poi[~bool_zero]
print(poi_nao_zero)

[3 3 6 2 4 5 4 4 2 3 3 2 8 2 3 3 3 4 4 2 6 6 3 4 3 5 2 1 3 2 2 3 2 4 4 5 7
 3 5 3 3 2 2 3 6 2 2 4 3 5 2 5 3 2 1 1 4 4 4 6 2 4 1 2 5 5 3 4 1 4 1 1 7 1
 2 1 3 7 4 4 6 1 3 4 2 5 4 5 5 3 4 6 8 2]
